---
apiVersion: v1
kind: Namespace
metadata:
  name: vsphere-bridge
---
apiVersion: v1
kind: Secret
metadata:
  name: password
  namespace: vsphere-bridge
stringData:
  key: "..."
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vsphere-bridge
    service: vsphere-bridge
  name: vsphere-bridge
  namespace: vsphere-bridge
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: vsphere-bridge
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vsphere-bridge
  namespace: vsphere-bridge
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vsphere-bridge
      version: v1
  template:
    metadata:
      labels:
        app: vsphere-bridge
        version: v1
    spec:
      containers:
        - env:
          - name: ALLOW_INSECURE
            value: "true"
          - name: VSPHERE_FQDN
            value: https://10.5.15.2
          - name: VSPHERE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: password
                key: key
          - name: VSPHERE_USERNAME
            value: administrator@vsphere.local
          image: docker.io/sjdaws/vsphere-bridge:latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            periodSeconds: 20
            timeoutSeconds: 2
          name: vsphere-bridge
          resources:
            limits:
              memory: 128Mi
            requests:
              cpu: 100m
